#!/bin/bash

# first argument is the name of the node
# second argument (X) is the number of other nodes
# the following X  arguments are the names of the other nodes
# the remaining arguments are the input files

#
# this script is intended and should work if we choose to configure all nodes at runtime when the
# user has finished building their network, it requires knowledge of it's neighbors and their names

# need to reset config to default before running this script (e.g. restart the node)

DEBUG="true"

ARGS=("$@")
NODENUM=${ARGS[0]}
NUM_OTHERNODES=${ARGS[1]}
OTHERNODES=()

#if the NODENUM is -, then take the name of the node from the hostname environment variable.
# WARNING - do not use this if running a network multiple times or manually naming the nodes. 
# only functions with autogenerated naming scheme of GNS3.
# DEPRECATED
if [ $NODENUM = "-" ] 
then
	NODENUM=$(cut -d "-" -f2- <<< "$(printenv HOSTNAME)")
	echo "node name set to HOSTNAME: $NODENUM"
fi

# extract array of the names of the other nodes given.
for NUM in $(seq 2 $(expr $NUM_OTHERNODES + 1 ) ); do
	OTHERNODES+=("${ARGS[$NUM]}")
done

# debug
if [ $DEBUG = "true" ] 
then
	echo "full args list: ${ARGS[@]}"
	echo "node name: $NODENUM"
	echo "num other nodes known: $NUM_OTHERNODES"
	echo "names of other nodes known: ${OTHERNODES[@]}"
	echo "ARG numbers that are files to change: $(seq $(expr 2 + $NUM_OTHERNODES) $(expr ${#ARGS[@]} - 1 ))"
fi

# fix the files given.
for NUM in $(seq $(expr 2 + $NUM_OTHERNODES) $(expr ${#ARGS[@]} - 1 )); do
	CONFIGUREDCONFFILENAME=$(echo ${ARGS[$NUM]} | sed "s/\(\.\)/$NODENUM\1/")
	touch $CONFIGUREDCONFFILENAME

	sed "s/<[xX]>/$NODENUM/g" ${ARGS[$NUM]} > $CONFIGUREDCONFFILENAME

	for I in ${OTHERNODES[@]}; do
		awk  "1; gsub(/<[yY]>/,"$I")" $CONFIGUREDCONFFILENAME > tmp && mv -f tmp $CONFIGUREDCONFFILENAME
	done
	sed -i "s/<[yY]>/$NODENUM/g" $CONFIGUREDCONFFILENAME
	sed -i "s/nx.ipnrc/nx$NODENUM.ipnrc/g" $CONFIGUREDCONFFILENAME
	
done

echo "conf_script complete"