FROM ubuntu AS image

# get some basics
RUN apt-get -y update
RUN apt-get -y install sudo

RUN apt-get -y install wget

RUN sudo apt update
RUN sudo apt install build-essential -y

# pull ion repo
RUN wget https://sourceforge.net/projects/ion-dtn/files/ion-open-source-4.1.0.tar.gz/download

# unpack
RUN tar xvzf download

# set work dir
WORKDIR /ion-open-source-4.1.0

# configure ION
RUN ./configure

# make ion
RUN make

RUN sudo make install

RUN sudo ldconfig

# switch back to root as working dir.
WORKDIR /root

# get ping - for testing
RUN apt update
RUN apt-get install iputils-ping -y
RUN apt install -y iproute2

# clean apt update list to save space.
RUN rm -rf /var/lib/apt/lists/*

# make directory for default configs
RUN mkdir ion_config

# copy script used to configure config files on individial node basis
COPY conf_script.sh ./ion_config/

# make script executable
RUN chmod +x ./ion_config/conf_script.sh

# copy default config files.
COPY nx.* ./ion_config/
